approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@lesjoursfr/browser-tools"
