name: Publish Package to npmjs

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - run: corepack enable
      - name: Use Node.js 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "26.4.0"
          package-manager-cache: false
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          yarn config set enableImmutableInstalls false
          yarn install

      - run: npm run build

      - run: npm publish --provenance
